add unittest
alibaba/heterogeneity-aware-lowering-and-optimization pull request #930
Opened 2022-06-13 05:20 UTC by chanzhennan

2022-06-17 03:28 UTC, jackzipu requested changes

2022-06-17 03:28 UTC, jackzipu commented on ODLA/platforms/odla_popart/test/odla_config_test.cc
> +
Need to add a function to check the default value of configuration, in case some one change it by mistake.

2022-06-17 03:28 UTC, jackzipu commented on ODLA/platforms/odla_popart/test/odla_ops_math_test.cc
> +// Copyright (C) 2019-2020 Alibaba Group Holding Limited.
2019-2020 should be 2022

2022-06-17 03:28 UTC, jackzipu commented on ODLA/platforms/odla_popart/test/odla_ops_math_test.cc
> +// Copyright (c) 2020 Graphcore Ltd. All rights reserved.
2020 should be 2022

2022-06-17 03:28 UTC, jackzipu commented on ODLA/platforms/odla_popart/test/odla_ops_nn_test.cc
> +  // SUBCASE("TOPK OPS TEST") {
TOPK has problem?

2022-06-18 05:44 UTC, chanzhennan commented
util commit [c3b5b62]
![image](https://user-images.githubusercontent.com/7290453/174424665-03b799e3-3929-4a4e-8956-9d7eaa31c509.png)

2022-06-19 17:09 UTC, chanzhennan commented
coverage on commit [5e8ca98]
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/7290453/174492515-8f24a57c-ef77-4235-b2bc-ee537876dbae.png">

2022-06-20 03:06 UTC, jackzipu commented on ODLA/platforms/odla_popart/test/odla_config_test.cc
> +}
应该增加一个检查config默认值的case，就是创建了config对象，但并没有读取config文件时候的默认值。应该和当前的默认值CHECK_EQ，以免后面的修改中错改了默认值。

2022-06-20 17:44 UTC, weimingzha0 commented
how to trigger the tests? Do we need to add them to CI tests?

2022-06-21 01:56 UTC, jackzipu approved these changes

2022-06-21 01:57 UTC, jackzipu approved these changes

2022-06-21 01:57 UTC, merged

2022-06-21 02:01 UTC, jackzipu commented
> how to trigger the tests? Do we need to add them to CI tests?

Hi Weiming, these tests only for ODLA POPART testing when we change the codes.  So we don't need to add to HALO CI I think, as it's not common for all platforms, only for ODLA POPART.

We added a readme for the test to show how to run it and generate the coverage report.